<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-07T13:31:13 EDT" name="Default Suite" finished-at="2023-05-07T13:31:21 EDT" duration-ms="7801">
    <groups>
    </groups>
    <test started-at="2023-05-07T13:31:13 EDT" name="BrokenLinkTest" finished-at="2023-05-07T13:31:21 EDT" duration-ms="7801">
      <class name="BrokenTest.BrokenTest">
        <test-method is-config="true" signature="main()[pri:0, instance:BrokenTest.BrokenTest@23986957]" started-at="2023-05-07T13:31:13 EDT" name="main" finished-at="2023-05-07T13:31:21 EDT" duration-ms="7720" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method signature="broken_Test()[pri:0, instance:BrokenTest.BrokenTest@23986957]" started-at="2023-05-07T13:31:21 EDT" name="broken_Test" finished-at="2023-05-07T13:31:21 EDT" duration-ms="45" status="FAIL">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[unknown protocol: javascript]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: unknown protocol: javascript
at java.base/java.net.URL.<init>(URL.java:771)
at java.base/java.net.URL.<init>(URL.java:646)
at java.base/java.net.URL.<init>(URL.java:582)
at BrokenTest.BrokenTest.broken_Test(BrokenTest.java:59)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- broken_Test -->
      </class> <!-- BrokenTest.BrokenTest -->
    </test> <!-- BrokenLinkTest -->
  </suite> <!-- Default Suite -->
</testng-results>
